### ISSUE TITLE
Example not working for 0.3.0

### ISSUE THREAD

**Issue by tangkhaiphuong** [steffengy/tiberius#72]
I tried example from https://docs.rs/tiberius/0.3.0/tiberius/

main.rs
``` rust
extern crate futures;
extern crate futures_state_stream;
extern crate tokio;
extern crate tiberius;
use futures::Future;
use futures_state_stream::StateStream;
use tokio::executor::current_thread;
use tiberius::SqlConnection;

fn main() {
 
   // 1: for windows we demonstrate the hardcoded variant
   // which is equivalent to:
   //     let conn_str = "server=tcp:localhost,1433;integratedSecurity=true;";
   //     let future = SqlConnection::connect(conn_str).and_then(|conn| {
   // and for linux we use the connection string from an environment variable
   let conn_str = if cfg!(windows) {
       "server=tcp:localhost,1433;integratedSecurity=true;".to_owned()
   } else {
       ::std::env::var("TIBERIUS_TEST_CONNECTION_STRING").unwrap()
   };

   let future = SqlConnection::connect(conn_str.as_str())
       .and_then(|conn| {
           conn.simple_query("SELECT 1+2").for_each(|row| {
               let val: i32 = row.get(0);
               assert_eq!(val, 3i32);
               Ok(())
           })
       })
       .and_then(|conn| conn.simple_exec("create table #Temp(gg int);"))
       .and_then(|(_, conn)| conn.simple_exec("UPDATE #Temp SET gg=1 WHERE gg=1"));
 
   current_thread::block_on_all(future).unwrap();
}
``` 
Cargo.toml

``` toml
[package]
name = "test-tiberius"
version = "0.1.0"
authors = ["Tăng Khải Phương <tangkhaiphuong@gmail.com>"]

[dependencies]
tiberius = "0.3.0"
futures = "0.1.23"
futures-state-stream = "0.2.0"
tokio = "0.1.7"
```

Then error:

``` bat
C:/Users/tkphuong.OMNICASADOM/.cargo/bin/cargo.exe check --all
    Checking database-notification-service v0.1.0 (file:///D:/Projects/omnicasa-database-notification-service)
error[E0599]: no method named `for_each` found for type `tiberius::stmt::QueryResult<tiberius::query::ResultSetStream<std::boxed::Box<dyn tiberius::BoxableIo>, tiberius::query::QueryStream<std::boxed::Box<dyn tiberius::BoxableIo>>>>` in the current scope
   --> src\main.rs:120:45
    |
120 |             conn.simple_query("SELECT 1+2").for_each(|row| {
    |                                             ^^^^^^^^
    |
    = note: the method `for_each` exists but the following trait bounds were not satisfied:
            `&mut tiberius::stmt::QueryResult<tiberius::query::ResultSetStream<std::boxed::Box<dyn tiberius::BoxableIo>, tiberius::query::QueryStream<std::boxed::Box<dyn tiberius::BoxableIo>>>> : futures_state_stream::StateStream`
            `&mut tiberius::stmt::QueryResult<tiberius::query::ResultSetStream<std::boxed::Box<dyn tiberius::BoxableIo>, tiberius::query::QueryStream<std::boxed::Box<dyn tiberius::BoxableIo>>>> : std::iter::Iterator`
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
    |
100 | use futures_state_stream::StateStream;
    |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `database-notification-service`.

To learn more, run the command again with --verbose.


```

**Comment by steffengy** [comment]
You need futures_state_stream version 0.1.

**Comment by steffengy** [comment]
will not be a problem, whatever happens in direction of #75

**Comment by young-altair** [comment]
Sorry to reopen this issue. I just started learning the Rust language and loved it, because before I was familiar with C ++ and Pascal. Then I have some school assignment related to the SQLServer database. After reading and trying the same code as Mr tangkhaiphuong, the code doesn't work. What makes me curious is why cargo always forces to use the latest version, even though I already set the version in dependency toml.
The compiler log :
```Updating crates.io index
   Compiling libc v0.2.62
   Compiling cfg-if v0.1.10
   Compiling semver-parser v0.7.0
   Compiling futures v0.1.29
   Compiling lazy_static v1.4.0
   Compiling log v0.4.8
   Compiling byteorder v1.3.2
   Compiling scopeguard v1.0.0
   Compiling slab v0.4.2
   Compiling arrayvec v0.4.12
   Compiling autocfg v0.1.6
   Compiling smallvec v0.6.10
   Compiling nodrop v0.1.14
   Compiling fnv v1.0.6
   Compiling encoding_index_tests v0.1.4
   Compiling bitflags v1.2.0
   Compiling md5 v0.3.8
   Compiling crossbeam-utils v0.6.6
   Compiling semver v0.9.0
   Compiling lock_api v0.3.1
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling rustc_version v0.2.3
   Compiling crossbeam-queue v0.1.2
   Compiling tokio-executor v0.1.8
   Compiling tokio-sync v0.1.7
   Compiling futures-state-stream v0.1.1
   Compiling encoding v0.2.33
   Compiling parking_lot_core v0.6.2
   Compiling memoffset v0.5.1
   Compiling parking_lot v0.9.0
   Compiling tokio-current-thread v0.1.6
   Compiling tokio-timer v0.2.11
   Compiling iovec v0.1.4
   Compiling num_cpus v1.10.1
   Compiling net2 v0.2.33
   Compiling rand v0.4.6
   Compiling time v0.1.42
   Compiling bytes v0.4.12
   Compiling mio v0.6.19
   Compiling winauth v0.0.3
   Compiling tokio-io v0.1.12
   Compiling crossbeam-epoch v0.7.2
   Compiling mio-uds v0.6.7
   Compiling tokio-codec v0.1.1
   Compiling chrono v0.4.9
   Compiling crossbeam-deque v0.7.1
   Compiling tokio-reactor v0.1.10
   Compiling tokio-threadpool v0.1.16
   Compiling tokio-uds v0.2.5
   Compiling tokio-tcp v0.1.3
   Compiling tokio-udp v0.1.5
   Compiling tokio-fs v0.1.6
   Compiling tokio v0.1.22
   Compiling tiberius v0.3.2
   Compiling testsql v0.1.0 (/home/yusren/Rust/testsql)
warning: use of deprecated item 'tokio::executor::current_thread': use tokio-current-thread crate or functions in tokio::runtime::current_thread instead
 --> src/main.rs:8:5
  |
8 | use tokio::executor::current_thread;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 43.96s
     Running `target/debug/testsql`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x560402a9fe84 - backtrace::backtrace::libunwind::trace::h26d1d81c2daef33a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x560402a9fe84 - backtrace::backtrace::trace_unsynchronized::hd05e28d6b468d728
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x560402a9fe84 - std::sys_common::backtrace::_print_fmt::hb5f1b0e3b0916d41
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x560402a9fe84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he07411646847de67
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x560402ac062c - core::fmt::write::h3a141994ffc15381
                               at src/libcore/fmt/mod.rs:1028
   5:     0x560402a9c7d7 - std::io::Write::write_fmt::hb6563315e12c4310
                               at src/libstd/io/mod.rs:1412
   6:     0x560402aa233e - std::sys_common::backtrace::_print::h24ad38915badf3d2
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x560402aa233e - std::sys_common::backtrace::print::hddefbfe45740d4aa
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x560402aa233e - std::panicking::default_hook::{{closure}}::h505480cde2d9da23
                               at src/libstd/panicking.rs:189
   9:     0x560402aa2041 - std::panicking::default_hook::h7fb28307afbcef54
                               at src/libstd/panicking.rs:206
  10:     0x560402aa2a35 - std::panicking::rust_panic_with_hook::h39f14bc4c2204167
                               at src/libstd/panicking.rs:469
  11:     0x560402aa25d2 - std::panicking::continue_panic_fmt::hc6add4646f39b121
                               at src/libstd/panicking.rs:376
  12:     0x560402aa24c6 - rust_begin_unwind
                               at src/libstd/panicking.rs:303
  13:     0x560402abc9ba - core::panicking::panic_fmt::h900fcd59bf7e2ab4
                               at src/libcore/panicking.rs:84
  14:     0x560402abcab7 - core::result::unwrap_failed::h7f0eef2751a47411
                               at src/libcore/result.rs:1165
  15:     0x5604028e252d - core::result::Result<T,E>::unwrap::h0b5188fbdab40e4e
                               at /rustc/898f36c83cc28d7921a1d7b3605323dc5cfcf533/src/libcore/result.rs:933
  16:     0x5604028ee19a - testsql::main::h8f95a12fad4915ba
                               at src/main.rs:21
  17:     0x5604028e0350 - std::rt::lang_start::{{closure}}::h6dd511cd0c9e0b1f
                               at /rustc/898f36c83cc28d7921a1d7b3605323dc5cfcf533/src/libstd/rt.rs:61
  18:     0x560402aa2463 - std::rt::lang_start_internal::{{closure}}::h47a609afac0a40a7
                               at src/libstd/rt.rs:48
  19:     0x560402aa2463 - std::panicking::try::do_call::hc478f49a705826db
                               at src/libstd/panicking.rs:288
  20:     0x560402aa5e4a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x560402aa2f2d - std::panicking::try::h03aae32bf82d446e
                               at src/libstd/panicking.rs:267
  22:     0x560402aa2f2d - std::panic::catch_unwind::h0d27fd0ff477064b
                               at src/libstd/panic.rs:394
  23:     0x560402aa2f2d - std::rt::lang_start_internal::hd9be77268850f0ba
                               at src/libstd/rt.rs:47
  24:     0x5604028e0329 - std::rt::lang_start::he7b217374b43e5d9
                               at /rustc/898f36c83cc28d7921a1d7b3605323dc5cfcf533/src/libstd/rt.rs:61
  25:     0x5604028ee2da - main
  26:     0x7fa2213a1b97 - __libc_start_main
  27:     0x5604028dd66a - _start
  28:                0x0 - <unknown>
```
As you can see, the tiberius version used is 0.3.2 and the tokio version v0.1.22. Even though I use dependencies with the same version as the example above.
I'm using : 
`rustc 1.40.0-nightly (898f36c83 2019-10-10)`
And my system are :
```
Ubuntu 18.04.3 LTS
Linux 4.15.0-65-generic
GTK 3.22.30
```
Please help and thanks

**Comment by steffengy** [comment]
As the stacktrace says, your problem is in src/main.rs:21
