### ISSUE TITLE
Panicked at 'called `Result::unwrap()` on an `Err` value: Canceled'

### ISSUE THREAD

**Issue by brokenthorn** [steffengy/tiberius#84]
I can't find the reason why my code panics. My repository is public, so here is the test that is failing: [`test_get_stock`](https://github.com/brokenthorn/bizpharma_webstore_interface_ws/blob/master/src/database/mod.rs).

The cause of the panic is in this fn:
```rust
/// Tries to fetch the current `StockList` and returns a future for that result.
    pub fn get_stock(&self) -> Box<Future<Item=Stock, Error=String> + Send> {
        let stock_future = self.create_connection()
            .and_then(|conn| {
                let querystring = "with rezumat_stoc_cte(location_id, article_id, acquisition_date, best_before_date, net_acquisition_price, gross_acquisition_price, added_value_percent, retail_price, vat_percent, fractions, whole_quantity, fraction_quantity) as (select IdLocatie as location_id, IdArticol as article_id, DataIntrare as acquisition_date, BBD as best_before_date, cast(PretAchizitie as decimal(8, 2)) as net_acquisition_price, cast(PretAchizitieNediscFTVA as decimal(8, 2)) as gross_acquisition_price, ProcAdaos as added_value_percent, cast(PretAmanunt as decimal(8, 2)) as retail_price, cast(ProcTVA as decimal(4, 2)) as vat_percent, CantNrBuc as fractions, SUM(CantI) as whole_quantity, SUM(CantF) as fraction_quantity from BizPharmaHO.dbo.Stoc group by IdLocatie, IdArticol, BBD, PretAchizitie, PretAchizitieNediscFTVA, PretAmanunt, ProcTVA, ProcAdaos, DataIntrare, CantNrBuc) select location_id, article_id, acquisition_date, best_before_date, net_acquisition_price, gross_acquisition_price, added_value_percent, retail_price, vat_percent, fractions, case when fraction_quantity < fractions then whole_quantity else whole_quantity + floor(fraction_quantity / fractions) end as whole_quantity, case when fraction_quantity < fractions then fraction_quantity else fraction_quantity - (floor(fraction_quantity / fractions) * fractions) end as fraction_quantity from rezumat_stoc_cte;";
                conn.simple_query(querystring)
                    .map(|row| {
                        StockLineItem {
                            location_id: row.get(0),
                            article_id: row.get(1),
                            acquisition_date: row.get(2),
                            best_before_date: row.get(3),
                            net_acquisition_price: row.get(4),
                            gross_acquisition_price: row.get(5),
                            added_value_percent: row.get(6),
                            retail_price: row.get(7),
                            vat_percent: row.get(8),
                            fractions: row.get(9),
                            whole_quantity: row.get(10),
                            fraction_quantity: row.get(11),
                        }
                    })
                    .collect()
                    .map(|collected| {
                        collected.0
                    })
            })
            .map_err(|err| {
                format!("An error occurred while executing `get_stock_list`: {:?}", err)
            });
        Box::new(stock_future)
    }
```

which is supposed to return a future for a `Stock` object (which is a `Vec<StockListItem>`). I'm using the latest stable rustc and tiberius' `master` branch. The error occurs inside tiberius but I can't understand why. Debugging it didn't help either. I appreciate any help I can get!

**Comment by brokenthorn** [comment]
So I found only one usage of `tiberius::Error::Canceled`. It's in [`query.rs:121`](https://github.com/steffengy/tiberius/blob/96ab7df567d3a4cde92f75af9724dc029ccbb96c/tiberius/src/query.rs#L121). What is this error used for? It looks like it might be an [unexpected cancellation](https://github.com/steffengy/tiberius/blob/96ab7df567d3a4cde92f75af9724dc029ccbb96c/tiberius/src/query.rs#L163) from the client side, at the TDS protocol level.

**Comment by brokenthorn** [comment]
I thought a stack trace would help. Looking at the trace below, I [this](https://github.com/steffengy/tiberius/blob/96ab7df567d3a4cde92f75af9724dc029ccbb96c/tiberius/src/query.rs#L132) where panic happens?

```shell
Testing started at 21:54 ...
/Users/sebastian/.cargo/bin/cargo test --color=always --package bizpharma_webstore_interface_ws --bin bizpharma_webstore_interface_ws database::tests::test_get_stock --no-fail-fast --all-features -- --exact -Z unstable-options --format=json
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running target/debug/deps/bizpharma_webstore_interface_ws-85c373cbfdcbacbb

thread 'database::tests::test_get_stock' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', libcore/result.rs:1009:5
stack backtrace:
   0:        0x106b4035f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd303b0cd45bccf60
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x106b3108d - std::sys_common::backtrace::print::hf2fe31942821bdcb
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x106b42f63 - std::panicking::default_hook::{{closure}}::h748cb38cc840cba6
                               at libstd/panicking.rs:211
   3:        0x106b42c8e - std::panicking::default_hook::h81d2ef89c2ad110e
                               at libstd/panicking.rs:221
   4:        0x106b43697 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hc265418ddf96c674
                               at libstd/panicking.rs:477
   5:        0x106b431fc - std::panicking::continue_panic_fmt::h2d9dbf1e069d262d
                               at libstd/panicking.rs:391
   6:        0x106b430e8 - std::panicking::try::do_call::hcfe6ac53944e0624
                               at libstd/panicking.rs:326
   7:        0x106b85521 - core::ptr::drop_in_place::h2136aea44990720c
                               at libcore/panicking.rs:77
   8:        0x1067992cd - core::result::unwrap_failed::h1047cd2cff38a5a9
                               at libcore/macros.rs:26
   9:        0x106798657 - <core::result::Result<T, E>>::unwrap::hc4b29bf7718cd11b
                               at libcore/result.rs:808
  10:        0x1067a4473 - <tiberius::query::ResultInner<I> as core::ops::drop::Drop>::drop::h326a338b3583ab6c
                               at /Users/sebastian/.cargo/git/checkouts/tiberius-efcdb30e5dbea5fc/c3d1447/tiberius/src/query.rs:132
  11:        0x1067a0934 - core::ptr::drop_in_place::h38bfb464be29d657
                               at libcore/ptr.rs:59
  12:        0x1067a0f84 - core::ptr::drop_in_place::h51b612ffd5130c8e
                               at libcore/ptr.rs:59
  13:        0x1067a06ae - core::ptr::drop_in_place::h27351f2b70242d6c
                               at libcore/ptr.rs:59
  14:        0x1067a179d - core::ptr::drop_in_place::h9140a4def5d8b330
                               at libcore/ptr.rs:59
  15:        0x1067a0d34 - core::ptr::drop_in_place::h4822743498d9bfd7
                               at libcore/ptr.rs:59
  16:        0x1067a1e45 - core::ptr::drop_in_place::hb32c510bad3903c3
                               at libcore/ptr.rs:59
  17:        0x1067a1354 - core::ptr::drop_in_place::h6975be0af6cd5696
                               at libcore/ptr.rs:59
  18:        0x1067a087d - core::ptr::drop_in_place::h373b55b80da952b0
                               at libcore/ptr.rs:59
  19:        0x1067a9c13 - <tokio_current_thread::Entered<'a, P>>::block_on::hc48362f60d00c80f
                               at /Users/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:494
  20:        0x1067a8f08 - <tokio_current_thread::CurrentThread<P>>::block_on::h375e240247a2575c
                               at /Users/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:340
  21:        0x1067a8851 - tokio_current_thread::block_on_all::heff7a7d1cd6b9bab
                               at /Users/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:229
  22:        0x1067ad90f - bizpharma_webstore_interface_ws::database::BizPharmaDatabase::get_stock::h1261670fc489adaf
                               at src/database/mod.rs:105
  23:        0x1067a59c8 - bizpharma_webstore_interface_ws::database::tests::test_get_stock::h04c65a761de39006
                               at src/database/mod.rs:158
  24:        0x1067ac690 - bizpharma_webstore_interface_ws::database::tests::test_get_stock::{{closure}}::hec84ed894041064d
                               at src/database/mod.rs:155
  25:        0x10679fd70 - core::ops::function::FnOnce::call_once::h18410124603193e4
                               at libcore/ops/function.rs:238
  26:        0x1067b16b1 - <F as alloc::boxed::FnBox<A>>::call_box::h002d33950a07b87f
                               at libtest/lib.rs:1461
                               at libcore/ops/function.rs:238
                               at liballoc/boxed.rs:646
  27:        0x106b5032e - macho_symbol_search
                               at libpanic_unwind/lib.rs:103
  28:        0x1067bcabc - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d15d105d1b37b8a
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libtest/lib.rs:1416
                               at libstd/sys_common/backtrace.rs:136
  29:        0x1067d5697 - std::panicking::try::do_call::hfc390e5c13aa30de
                               at libstd/thread/mod.rs:409
                               at libstd/panic.rs:313
                               at libstd/panicking.rs:310
  30:        0x106b5032e - macho_symbol_search
                               at libpanic_unwind/lib.rs:103
  31:        0x1067c5f14 - <F as alloc::boxed::FnBox<A>>::call_box::h666b1399f6211e92
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/thread/mod.rs:408
                               at liballoc/boxed.rs:646
  32:        0x106b42627 - std::sys_common::thread::start_thread::ha68f94e048f96d59
                               at liballoc/boxed.rs:656
                               at libstd/sys_common/thread.rs:24
  33:        0x106b30148 - std::sys::unix::thread::Thread::new::thread_start::h57baa5b47ae41e12
                               at libstd/sys/unix/thread.rs:90
  34:     0x7fff69d16338 - _pthread_body
  35:     0x7fff69d192a6 - _pthread_start

error: test failed, to rerun pass '--bin bizpharma_webstore_interface_ws'

Process finished with exit code 101
```

**Comment by steffengy** [comment]
Can't reproduce without the underlying DB data.

Yes that's the right point where the panic happens.
I don't quite see how that error occurs, but I can provide a high-level explanation for what it's used for for you (Disclaimer ahead: quite complex):

- If you call simple_query, a `QueryResult` [is created](https://github.com/steffengy/tiberius/blob/a2d81efff3c78b85722b8608d764e3040413be9b/tiberius/src/stmt.rs#L2789). This query result wraps a ResultSetStream, which is a stream of resultsets. Executing 2 queries e.g. yields 2 resultsets (=QueryStreams) and QueryResult is the wrapper for the common case where there is only 1 resultset.
- The ResultSetStream [transfers the ownership](https://github.com/steffengy/tiberius/blob/master/tiberius/src/query.rs#L94-L98) of the connection (temporarily) to the current QueryStream, so we can read columns etc..
- The QueryStream can perform the work and after it's fully processed, it returns the connection to the [ResultSetStream](https://github.com/steffengy/tiberius/blob/96ab7df567d3a4cde92f75af9724dc029ccbb96c/tiberius/src/query.rs#L163).
- The ResultSetStream [receives the connection back](https://github.com/steffengy/tiberius/blob/96ab7df567d3a4cde92f75af9724dc029ccbb96c/tiberius/src/query.rs#L51), and in the case of only 1 query would return None, since the handling of every resultset is already done.

The Canceled error can only occur if the receiver (ResultSetStream) is dropped before the QueryStream, which should never be possible.

**Comment by steffengy** [comment]
Reproduced. Thanks for that!

**Comment by bbigras** [comment]
Thanks!
